#!/usr/bin/env python3
"""Bundle the on-device comics renderer into a self-contained HTML string.

Reads mobile/render/comics_draw.js and the three fonts in assets/fonts, embeds
the fonts as base64 @font-face rules, and writes mobile/render/rendererHtml.js
(export const RENDERER_HTML). The mobile app loads that string into a WebView so
the whole renderer works offline with no external font/network dependency.

Run from the repo root after editing comics_draw.js:
    python scripts/build_renderer.py
"""
import base64
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "assets" / "fonts"
DRAW = ROOT / "mobile" / "render" / "comics_draw.js"
OUT = ROOT / "mobile" / "render" / "rendererHtml.js"


def _b64(name: str) -> str:
    return base64.b64encode((FONTS / name).read_bytes()).decode()


def main() -> None:
    bebas = _b64("BebasNeue-Regular.ttf")
    osw = _b64("Oswald-Regular.ttf")
    oswb = _b64("Oswald-Bold.ttf")
    draw = DRAW.read_text()

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
@font-face{{font-family:'BebasNeue';src:url(data:font/ttf;base64,{bebas}) format('truetype');}}
@font-face{{font-family:'Oswald';src:url(data:font/ttf;base64,{osw}) format('truetype');}}
@font-face{{font-family:'OswaldBold';src:url(data:font/ttf;base64,{oswb}) format('truetype');}}
html,body{{margin:0;background:#0a0a0a;color:#666;font-family:Oswald;}}
</style></head><body>
<script>{draw}</script>
<script>
function post(msg){{ if(window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(msg)); }}
async function handle(payload){{
  try {{
    const out = await window.renderComics(payload.data);
    post({{ type:'slides', slides: out }});
  }} catch (e) {{ post({{ type:'error', error: String(e && e.message || e) }}); }}
}}
function onMsg(ev){{
  try {{ const m = JSON.parse(ev.data); if (m && m.type==='render') handle(m); }} catch(e){{}}
}}
document.addEventListener('message', onMsg);
window.addEventListener('message', onMsg);
post({{ type:'ready' }});
</script>
</body></html>"""

    esc = html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    OUT.write_text(
        "// AUTO-GENERATED by scripts/build_renderer.py — do not edit by hand.\n"
        "// Self-contained comics renderer (fonts + canvas engine) for the WebView.\n"
        f"export const RENDERER_HTML = `{esc}`;\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
