# DO NOT COMMIT THIS FILE
$env:IG_ACCESS_TOKEN="PASTE_FULL_LONG_TOKEN_HERE"
$env:IG_BUSINESS_ACCOUNT_ID="17841477579530391"
$env:IG_API_VERSION="v20.0"
Write-Host "CHANGED + SAVED: IG env vars loaded into this session"
